Repository entando-k8s/entando-k8s-plugin-controller, pull requests merged in 2020-10, with the labels that each got.

#13 ENG-872 bumped to latest dependencies and adapted code
  charts/preview/templates/operator-role.yaml
  pom.xml
  src/main/java/org/entando/kubernetes/controller/plugin/EntandoPluginController.java
  src/main/java/org/entando/kubernetes/controller/plugin/EntandoPluginDeployableContainer.java
  src/main/java/org/entando/kubernetes/controller/plugin/EntandoPluginDeploymentResult.java
  src/main/java/org/entando/kubernetes/controller/plugin/EntandoPluginServerDeployable.java
  src/test/java/org/entando/kubernetes/controller/plugin/inprocesstests/DeployPluginOnExternalDbTest.java
  src/test/java/org/entando/kubernetes/controller/plugin/inprocesstests/DeployPluginTest.java
  src/test/java/org/entando/kubernetes/controller/plugin/inprocesstests/DeployPluginWithoutDbTest.java
  src/test/java/org/entando/kubernetes/controller/plugin/inprocesstests/DeployPluginWithoutSidecarTest.java
  src/test/java/org/entando/kubernetes/controller/plugin/interprocesstests/AddEntandoPluginBaseIT.java
  src/test/java/org/entando/kubernetes/controller/plugin/interprocesstests/AddEntandoPluginWithEmbeddedDatabaseIT.java
  src/test/java/org/entando/kubernetes/controller/plugin/interprocesstests/AddEntandoPluginWithExternalOracleDatabaseIT.java
  src/test/java/org/entando/kubernetes/controller/plugin/interprocesstests/AddEntandoPluginWithExternalPostgresqlDatabaseIT.java
Labels: approved, size/L

#14 ENG-3129 bumped to latest operator-common
  pom.xml
  src/main/java/org/entando/kubernetes/controller/plugin/EntandoPluginDeployableContainer.java
  src/main/java/org/entando/kubernetes/controller/plugin/EntandoPluginSidecarDeployableContainer.java
  src/test/java/org/entando/kubernetes/controller/plugin/inprocesstests/DeployPluginOnExternalDbTest.java
  src/test/java/org/entando/kubernetes/controller/plugin/inprocesstests/DeployPluginTest.java
Labels: approved, size/S

#15 Firegloves into owners
  OWNERS
Labels: size/XS
